spring:
  application:
    name: enefitresourceservice

  datasource:
    url: jdbc:postgresql://localhost:5432/enefitresourceservice
    username: enefitresourceservice_user
    password: enefitresourceservice_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: localhost:9092

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    resolve-schema-properties: true

logging:
  level:
    com.kaarelkaasla.enefitresourceservice: DEBUG
    org.springframework.kafka: INFO

app:
  kafka:
    topic:
      resource-updates: resource-updates
  timezone: Europe/Tallinn
